name: Check Builds

on:
  push:
    paths:
        - src/**
        - main.c
        - Makefile
        - CMakeLists.txt
        - .github/workflows/check-build.yaml

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest-4-cores
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: CMake
        run: cmake -B build
      - name: Build
        run: cmake --build build
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: Cosmo-Ubuntu
          path: bin

  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Create CMake build files
        run: cmake -B build -DCMAKE_BUILD_TYPE=MinSizeRel
      - name: Check compilation
        run: cmake --build build --config MinSizeRel
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: Cosmo-Windows
          path: bin